services:
  jenkins:
    image: jenkins/jenkins:2.526-jdk21
    container_name: jenkins
    user: root
    privileged: true
    ports:
      - "3001:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_docker_certs:/certs/client:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    networks:
      - jenkins
volumes:
  jenkins_data:
  jenkins_docker_certs:

networks:
  jenkins:
    driver: bridge