services:
  docker-dind:
    image: docker:27-dind
    container_name: docker-dind
    user: root
    privileged: true
    ports:
      - 2376:2376
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_docker_certs:/certs/client
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    restart: on-failure
    networks:
      jenkins:
        aliases:
          - docker

  jenkins:
    image: jenkins/jenkins:2.526-jdk21
    container_name: jenkins
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_docker_certs:/certs/client:ro
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: "1"
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    depends_on:
      - docker-dind
    restart: on-failure
    networks:
      - jenkins

volumes:
  jenkins_data:
  jenkins_docker_certs:

networks:
  jenkins:
    driver: bridge
